# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    workingDirectory: 'OnlineTeamScan_V2_BE'
    
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*.test.csproj'
    workingDirectory: 'OnlineTeamScan_V2_BE'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: 'OnlineTeamScan_V2_BE'
    zipAfterPublish: true

- task: FileTransform@1
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/**/*.zip'
    fileType: 'json'
    targetFiles: '**/appsettings.json'